services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom_pass
      POSTGRES_DB: ecommerce
    ports:
      - "5555:5432"
    volumes:
      - pg_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  pg_dev_data:
  redis_dev_data:
