-- ============================================================
-- Nefesol Shop — Ürün Seed (her kategoride 1 ürün + 1 varyant)
-- 25 ürün + 25 varyant. Fiyatlar KDV HARİÇ (net), vat_included=false, vat_rate=18.
-- Stok = 100, is_active = true. Tekrar çalıştırmak güvenli (ON CONFLICT DO NOTHING).
-- ÖN KOŞUL: categories_seed.sql önce yüklenmiş olmalı (FK: category_id).
-- Kullanım: docker compose exec -T postgres psql -U ecom -d ecommerce < products_seed.sql
-- ============================================================

BEGIN;

-- ── Ürünler ─────────────────────────────────────────────────
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-ev-yasam-tekstil','cmqe2hpkv000d6oic07xnepmo','Çok Amaçlı Saklama Kutusu Seti','urun-ev-yasam-tekstil','Çok Amaçlı Saklama Kutusu Seti',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-elektronik-teknoloji','cmqe2jfvg000k6oich6t0aax3','Kablosuz Bluetooth Kulaklık','urun-elektronik-teknoloji','Kablosuz Bluetooth Kulaklık',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-giyim-moda-fashion','cmqe29yhk00006oicdpg4en5g','Unisex Oversize Sweatshirt','urun-giyim-moda-fashion','Unisex Oversize Sweatshirt',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-kozmetik-kisisel-bakim','cmqe2kp8s000t6oicv2fp8pgo','Nemlendirici Cilt Bakım Seti','urun-kozmetik-kisisel-bakim','Nemlendirici Cilt Bakım Seti',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-spor-acik-hava','cmqe2lusw00126oicsfjfxd1x','Katlanır Kamp Sandalyesi','urun-spor-acik-hava','Katlanır Kamp Sandalyesi',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-etek','cmqe2bza2000c6oic5t8r2vcd','Klasik Midi Etek','urun-etek','Klasik Midi Etek',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-elbise','cmqe2anoc00026oictbewodnj','Şifon Yazlık Elbise','urun-elbise','Şifon Yazlık Elbise',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-tisort','cmqe2b6yh00046oicfr5oef9k','Pamuklu Basic Tişört','urun-tisort','Pamuklu Basic Tişört',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-gomlek','cmqe2bdau00066oicwl8ual86','Slim Fit Keten Gömlek','urun-gomlek','Slim Fit Keten Gömlek',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-ceket-mont','cmqe2blaq00086oics08ydvkv','Su Geçirmez Şişme Mont','urun-ceket-mont','Su Geçirmez Şişme Mont',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-pantolon','cmqe2br0u000a6oich2oub56l','Yüksek Bel Kumaş Pantolon','urun-pantolon','Yüksek Bel Kumaş Pantolon',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-ev-tekstili','cmqe2ib4f000f6oic6julvfej','Çift Kişilik Nevresim Takımı','urun-ev-tekstili','Çift Kişilik Nevresim Takımı',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-mobilya','cmqe2iuo6000j6oicqyq5qan5','Ahşap Yan Sehpa','urun-mobilya','Ahşap Yan Sehpa',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-ev-dekorasyonu','cmqe2inkb000h6oicr1iyfx4e','Dekoratif Masa Lambası','urun-ev-dekorasyonu','Dekoratif Masa Lambası',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-telefon-aksesuarlar','cmqe2jo6h000m6oicq9znz8jl','Hızlı Şarj Power Bank 20000mAh','urun-telefon-aksesuarlar','Hızlı Şarj Power Bank 20000mAh',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-kucuk-ev-aletleri','cmqe2kgmo000s6oicnzvg8qio','Çelik Su Isıtıcısı 1.7L','urun-kucuk-ev-aletleri','Çelik Su Isıtıcısı 1.7L',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-televizyon-ses-sistemleri','cmqe2k644000q6oiciultld84','Taşınabilir Bluetooth Hoparlör','urun-televizyon-ses-sistemleri','Taşınabilir Bluetooth Hoparlör',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-bilgisayar-tablet','cmqe2jxpi000o6oicxr7zpkuo','Kablosuz Klavye ve Mouse Seti','urun-bilgisayar-tablet','Kablosuz Klavye ve Mouse Seti',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-makyaj','cmqe2l4d0000x6oiceif97fyp','16 Renk Göz Farı Paleti','urun-makyaj','16 Renk Göz Farı Paleti',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-cilt-bakimi','cmqe2kybg000v6oicp1mvrak3','C Vitamini Yüz Serumu','urun-cilt-bakimi','C Vitamini Yüz Serumu',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-sac-bakimi','cmqe2leey000z6oicztd6222d','Onarıcı Saç Bakım Şampuanı','urun-sac-bakimi','Onarıcı Saç Bakım Şampuanı',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-parfum-deodorant','cmqe2ln2200116oicywurvnyf','Erkek Parfüm 100ml','urun-parfum-deodorant','Erkek Parfüm 100ml',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-spor-giyim-ayakkabi','cmqe2mfjx00146oicifvmk63u','Hafif Koşu Ayakkabısı','urun-spor-giyim-ayakkabi','Hafif Koşu Ayakkabısı',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-spor-branslari','cmqe2muug00166oicbhq65s3i','Profesyonel Futbol Topu','urun-spor-branslari','Profesyonel Futbol Topu',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, category_id, name, slug, description, is_active, is_featured, vat_rate, vat_included, pricing_method, created_at, updated_at) VALUES ('seedp-fitness-pilates','cmqe2n5of00186oicehnj4pc4','Kaymaz Pilates Matı','urun-fitness-pilates','Kaymaz Pilates Matı',true,false,18,false,'fixed',now(),now()) ON CONFLICT (id) DO NOTHING;

-- ── Varyantlar (fiyat = net / KDV hariç, stok 100) ──────────
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-ev-yasam-tekstil','seedp-ev-yasam-tekstil','SEED-EV-YASAM-TEKSTIL',250,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-elektronik-teknoloji','seedp-elektronik-teknoloji','SEED-ELEKTRONIK-TEKNOLOJI',750,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-giyim-moda-fashion','seedp-giyim-moda-fashion','SEED-GIYIM-MODA-FASHION',400,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-kozmetik-kisisel-bakim','seedp-kozmetik-kisisel-bakim','SEED-KOZMETIK-KISISEL-BAKIM',320,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-spor-acik-hava','seedp-spor-acik-hava','SEED-SPOR-ACIK-HAVA',600,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-etek','seedp-etek','SEED-ETEK',350,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-elbise','seedp-elbise','SEED-ELBISE',550,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-tisort','seedp-tisort','SEED-TISORT',180,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-gomlek','seedp-gomlek','SEED-GOMLEK',420,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-ceket-mont','seedp-ceket-mont','SEED-CEKET-MONT',1200,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-pantolon','seedp-pantolon','SEED-PANTOLON',480,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-ev-tekstili','seedp-ev-tekstili','SEED-EV-TEKSTILI',650,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-mobilya','seedp-mobilya','SEED-MOBILYA',900,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-ev-dekorasyonu','seedp-ev-dekorasyonu','SEED-EV-DEKORASYONU',450,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-telefon-aksesuarlar','seedp-telefon-aksesuarlar','SEED-TELEFON-AKSESUARLAR',520,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-kucuk-ev-aletleri','seedp-kucuk-ev-aletleri','SEED-KUCUK-EV-ALETLERI',480,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-televizyon-ses-sistemleri','seedp-televizyon-ses-sistemleri','SEED-TELEVIZYON-SES-SISTEMLERI',850,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-bilgisayar-tablet','seedp-bilgisayar-tablet','SEED-BILGISAYAR-TABLET',600,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-makyaj','seedp-makyaj','SEED-MAKYAJ',280,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-cilt-bakimi','seedp-cilt-bakimi','SEED-CILT-BAKIMI',240,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-sac-bakimi','seedp-sac-bakimi','SEED-SAC-BAKIMI',160,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-parfum-deodorant','seedp-parfum-deodorant','SEED-PARFUM-DEODORANT',700,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-spor-giyim-ayakkabi','seedp-spor-giyim-ayakkabi','SEED-SPOR-GIYIM-AYAKKABI',950,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-spor-branslari','seedp-spor-branslari','SEED-SPOR-BRANSLARI',380,100,true,now()) ON CONFLICT (id) DO NOTHING;
INSERT INTO product_variants (id, product_id, sku, price, stock_qty, is_active, created_at) VALUES ('seedv-fitness-pilates','seedp-fitness-pilates','SEED-FITNESS-PILATES',300,100,true,now()) ON CONFLICT (id) DO NOTHING;

COMMIT;

-- Doğrulama:
-- SELECT c.name, p.name, v.price FROM products p JOIN categories c ON c.id=p.category_id JOIN product_variants v ON v.product_id=p.id WHERE p.id LIKE 'seedp-%' ORDER BY c.sort_order;
